system:
    default:
        yui:
            modules:
                ezs-landingpagebasicsviewplugin:
                    requires: ['plugin', 'base', 'ez-pluginregistry', 'ezs-textareafieldview']
                    dependencyOf:
                    - 'ezs-landingpagebasicsview'
                    path: %richtext_block.public_dir%/js/apps/plugins/ezs-landingpagebasicsviewplugin.js
                ezs-landingpageviewservicesplugin:
                    requires: ['ez-viewservicebaseplugin', 'ez-pluginregistry', 'ez-searchplugin']
                    dependencyOf:
                    - 'ezs-dynamiclandingpagecreatorviewservice'
                    - 'ezs-dynamiclandingpageeditorviewservice'
                    path: %richtext_block.public_dir%/js/apps/plugins/ezs-landingpageviewservicesplugin.js
                ezs-richtextplugin:
                  requires: ['plugin', 'base', 'ez-pluginregistry']
                  dependencyOf:
                    - 'ezs-blockpopupformview'
                  path: %richtext_block.public_dir%/js/apps/plugins/ezs-richtextplugin.js
                ezs-richtextfieldview:
                  requires:
                    - 'ezs-fieldview'
                    - 'ez-alloyeditor'
                    - 'ez-alloyeditor-plugin-embed'
                    - 'ez-alloyeditor-plugin-addcontent'
                    - 'ez-alloyeditor-plugin-removeblock'
                    - 'ez-alloyeditor-plugin-focusblock'
                    - 'ez-alloyeditor-plugin-paste'
                    - 'ez-alloyeditor-plugin-yui3'
                    - 'ez-alloyeditor-toolbar-ezadd'
                    - 'ez-alloyeditor-toolbar-config-link'
                    - 'ez-alloyeditor-toolbar-config-text'
                    - 'ez-alloyeditor-toolbar-config-table'
                    - 'ez-alloyeditor-toolbar-config-heading'
                    - 'ez-alloyeditor-toolbar-config-paragraph'
                    - 'ez-alloyeditor-toolbar-config-embed'
                    - 'ez-alloyeditor-toolbar-config-image'
                    - 'ez-alloyeditor-button-heading'
                    - 'ez-alloyeditor-button-paragraph'
                    - 'ez-alloyeditor-button-list'
                    - 'ez-alloyeditor-button-embed'
                    - 'ez-alloyeditor-button-image'
                    - 'ez-alloyeditor-button-imagevariation'
                    - 'ez-alloyeditor-button-embedcenter'
                    - 'ez-alloyeditor-button-embedright'
                    - 'ez-alloyeditor-button-embedleft'
                    - 'ez-alloyeditor-button-blocktextalignleft'
                    - 'ez-alloyeditor-button-blocktextaligncenter'
                    - 'ez-alloyeditor-button-blocktextalignright'
                    - 'ez-alloyeditor-button-blocktextalignjustify'
                    - 'ez-alloyeditor-button-blockremove'
                    - 'ez-alloyeditor-button-embedhref'
                    - 'ez-alloyeditor-button-imagehref'
                    - 'ez-processable'
                    - 'ez-richtext-resolveembed'
                    - 'ez-richtext-resolveimage'
                    - 'ez-editorcontentprocessorxhtml5edit'
                    - 'ez-editorcontentprocessorremoveids'
                    - 'ez-editorcontentprocessoremptyembed'
                    - 'ez-editorcontentprocessorremoveanchors'
                    - 'studiorichtextfieldview-ez-template'
                  dependencyOf:
                    - 'ezs-formview'
                  path: %richtext_block.public_dir%/js/views/fields/ezs-richtextfieldview.js
                studiorichtextfieldview-ez-template:
                  type: 'template'
                  path: %richtext_block.public_dir%/templates/fields/edit/richtext.hbt
